CREATE TABLE `items` (
    `id`         INTEGER NOT NULL AUTO_INCREMENT,
    `name`       VARCHAR(80) NOT NULL,
    `stock`      INTEGER NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);