CREATE TABLE `clients` (
    `id`         INTEGER NOT NULL AUTO_INCREMENT,
    `fullname`   VARCHAR(100) NOT NULL,
    `email`      VARCHAR(128) NOT NULL,
    `phone`      VARCHAR(12) NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);